# Generated by Django 4.2.4 on 2024-05-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Country Name')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Country Code')),
                ('telephone_code', models.CharField(max_length=50, verbose_name='Telephone code')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countrys',
            },
        ),
    ]
