# Generated by Django 4.2.4 on 2023-08-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FIRcode',
            fields=[
                ('fir_code_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='FIR Code number')),
                ('description', models.CharField(max_length=350, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'FIRcode',
                'verbose_name_plural': 'FIRcodes',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='Shop Number')),
                ('shop_name', models.CharField(max_length=250, verbose_name='Shop Name')),
                ('shop_short_name', models.CharField(max_length=250, verbose_name='Shop Short Name')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
        ),
    ]
