# Generated by Django 4.2.4 on 2024-05-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name="Supplier's Code")),
                ('mfg_supplier_name', models.CharField(max_length=250, verbose_name='Mfg. Supplier Name')),
                ('mfg_supplier_short_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Short Name')),
                ('address', models.TextField(max_length=1000, verbose_name='Address')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('telephone', models.CharField(max_length=20, verbose_name='Telephone')),
                ('fax_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax Number')),
                ('email_id', models.EmailField(max_length=254, verbose_name='Email Id')),
                ('contact_person', models.CharField(max_length=250, verbose_name='Contact Person')),
                ('mobile_number', models.CharField(max_length=50, verbose_name='Mobile Number')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
    ]
