# Generated by Django 4.2.4 on 2024-05-23 14:24

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Manufacturer', '0001_initial'),
        ('Shop', '0001_initial'),
        ('Suppliers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Equipemnt Number')),
                ('description', models.CharField(max_length=350, verbose_name='Description')),
                ('short_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Short Name')),
                ('bay', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bay')),
                ('column', models.CharField(blank=True, max_length=50, null=True, verbose_name='Column')),
                ('section', models.CharField(blank=True, max_length=50, null=True, verbose_name='Section')),
                ('section_eln', models.CharField(blank=True, max_length=50, null=True, verbose_name='Section ELN')),
                ('equipment_type', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=50, null=True, verbose_name='Equipment Type')),
                ('sr_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='M/C Sr. No. Alloted by Mfg.')),
                ('model_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='M/C Model Number')),
                ('indian_agent', models.BooleanField(blank=True, null=True, verbose_name='Indian Agent')),
                ('make', models.CharField(blank=True, max_length=50, null=True, verbose_name='Make')),
                ('cost', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cost')),
                ('cost_in_lakhs', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cost in Lakhs')),
                ('po_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='PO Number')),
                ('po_date', models.DateField(blank=True, null=True, verbose_name='PO Date')),
                ('ptc_issue_date', models.DateField(blank=True, null=True, verbose_name='PTC Issue Date')),
                ('warranty', models.CharField(blank=True, max_length=50, null=True, verbose_name='Warranty(from the date of commissioning and proving out of MnP)')),
                ('amc_covered_in_po', models.BooleanField(blank=True, null=True, verbose_name='AMC covered in PO')),
                ('amc_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type of AMC')),
                ('amc_validity', models.DateField(blank=True, null=True, verbose_name='Validity of AMC')),
                ('recovery_value_warranty', models.CharField(blank=True, max_length=50, null=True, verbose_name='Recovery Value in Warranty Period')),
                ('percentage_avalability_in_warranty', models.CharField(blank=True, max_length=50, null=True, verbose_name='%age Availability in Warranty Period')),
                ('specification', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Specifications')),
                ('machine_image', models.BinaryField(blank=True, editable=True, null=True, verbose_name='machine_image')),
                ('po_copy', models.BinaryField(blank=True, editable=True, null=True, verbose_name='po_copy')),
                ('manufacturer_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Manufacturer.manufacturer', verbose_name='Manufacturer Code')),
                ('shop_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.shop', verbose_name='Shop Number')),
                ('supplier_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Suppliers.supplier', verbose_name='Supplier Code')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
            },
        ),
        migrations.CreateModel(
            name='EquipmentStatics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField(default=True, verbose_name='FLAG')),
                ('at_number', models.CharField(max_length=100, verbose_name='AT. No.')),
                ('date', models.DateField(verbose_name='Date')),
                ('date_of_commissionning', models.DateField(verbose_name='Date of Commissionning')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('contact_person', models.CharField(max_length=50, verbose_name='Contact Person')),
                ('fax', models.CharField(blank=True, max_length=50, null=True, verbose_name='FAX')),
                ('technical_parameters', django_quill.fields.QuillField(blank=True, null=True)),
                ('present_usage', django_quill.fields.QuillField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.shop', verbose_name='Location')),
                ('machine_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipment.equipment', verbose_name='Identification Number')),
            ],
            options={
                'verbose_name': 'EquipmentStatics',
                'verbose_name_plural': 'EquipmentStatics',
            },
        ),
        migrations.CreateModel(
            name='EquipmentSpare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_list_number', models.IntegerField(verbose_name='PL No.')),
                ('description', models.CharField(max_length=50, verbose_name='Sp. Description')),
                ('part_number', models.IntegerField(verbose_name='Part Number')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('sp_d', models.CharField(max_length=50, verbose_name='SP D')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('currency', models.CharField(max_length=50, verbose_name='Currency')),
                ('unit_price', models.FloatField(max_length=40, verbose_name='Unit Price')),
                ('total_price', models.FloatField(max_length=50, verbose_name='Total Price')),
                ('ledger_number', models.CharField(max_length=50, verbose_name='Ledger Detail')),
                ('remarks', models.CharField(max_length=500, verbose_name='Remarks')),
                ('machine_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipment.equipment', verbose_name='M/C NO.')),
            ],
            options={
                'verbose_name': 'EquipmentSpare',
                'verbose_name_plural': 'EquipmentSpares',
            },
        ),
    ]
