# Generated by Django 4.2.4 on 2023-08-03 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Suppliers', '0001_initial'),
        ('Manufacturer', '0001_initial'),
        ('Equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='amc_covered_in_po',
            field=models.BooleanField(blank=True, null=True, verbose_name='AMC covered in PO'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='amc_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type of AMC'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='amc_validity',
            field=models.DateField(blank=True, null=True, verbose_name='Validity of AMC'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='bay',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bay'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='column',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Column'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='cost',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='cost_in_lakhs',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cost in Lakhs'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Equipment Type'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='indian_agent',
            field=models.BooleanField(blank=True, null=True, verbose_name='Indian Agent'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='machine_image',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='Machine Image'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='make',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Make'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Manufacturer.manufacturer', verbose_name='Manufacturer Code'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='M/C Model Number'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='percentage_avalability_in_warranty',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='%age Availability in Warranty Period'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='po_copy',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='PO Copy'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='po_date',
            field=models.DateField(blank=True, null=True, verbose_name='PO Date'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='po_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PO Number'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='ptc_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='PTC Issue Date'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='recovery_value_warranty',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Recovery Value in Warranty Period'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='section_eln',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Section ELN'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='specification',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Specifications'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='sr_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='M/C Sr. No. Alloted by Mfg.'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='supplier_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Suppliers.supplier', verbose_name='Supplier Code'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='warranty',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Warranty(from the date of commissioning and proving out of MnP)'),
        ),
    ]
