# Generated by Django 4.2.4 on 2024-05-23 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='date_of_commissioning',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Commossioning'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='received_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='received date'),
            preserve_default=False,
        ),
    ]
