# Generated by Django 4.2.4 on 2024-05-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0002_remove_equipment_machine_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='machine_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='machine_image'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='po_copy',
            field=models.FileField(blank=True, null=True, upload_to='Equipments', verbose_name='po_copy'),
        ),
    ]
