# Generated by Django 4.2.4 on 2023-08-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0002_alter_equipment_amc_covered_in_po_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='machine_image',
        ),
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='machine_image'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='po_copy',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='po_copy'),
        ),
    ]
