# Generated by Django 4.2.4 on 2023-08-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0003_remove_equipment_machine_image_equipment_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='machine_image'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='po_copy',
            field=models.TextField(blank=True, null=True, verbose_name='po_copy'),
        ),
    ]
