# Generated by Django 4.2.4 on 2024-05-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0003_equipment_machine_image_equipment_po_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='machine_image',
            field=models.FileField(blank=True, null=True, upload_to='Equipments', verbose_name='machine_image'),
        ),
    ]
