# Generated by Django 4.2.4 on 2023-08-03 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0004_alter_equipment_image_alter_equipment_po_copy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='image',
            new_name='machine_image',
        ),
    ]
