# Generated by Django 4.2.4 on 2023-08-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0005_rename_image_equipment_machine_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='machine_image',
        ),
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='machine_image'),
        ),
    ]
