# Generated by Django 4.2.4 on 2023-08-03 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0006_remove_equipment_machine_image_equipment_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='image',
            new_name='machine_image',
        ),
    ]
