# Generated by Django 4.2.4 on 2023-08-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0007_rename_image_equipment_machine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='po_copy',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='po_copy'),
        ),
    ]
