# Generated by Django 4.2.4 on 2023-08-03 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Equipment', '0008_alter_equipment_po_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentSpare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_list_number', models.IntegerField(verbose_name='PL No.')),
                ('description', models.CharField(max_length=50, verbose_name='Sp. Description')),
                ('part_number', models.IntegerField(verbose_name='Part Number')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('sp_d', models.CharField(max_length=50, verbose_name='SP D')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('currency', models.CharField(max_length=50, verbose_name='Currency')),
                ('unit_price', models.FloatField(max_length=40, verbose_name='Unit Price')),
                ('total_price', models.FloatField(max_length=50, verbose_name='Total Price')),
                ('ledger_number', models.CharField(max_length=50, verbose_name='Ledger Detail')),
                ('remarks', models.CharField(max_length=500, verbose_name='Remarks')),
                ('machine_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipment.equipment', verbose_name='M/C NO.')),
            ],
            options={
                'verbose_name': 'EquipmentSpare',
                'verbose_name_plural': 'EquipmentSpares',
            },
        ),
    ]
