# Generated by Django 4.2.4 on 2024-05-23 06:20

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
        ('Equipment', '0009_equipmentspare'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentStatics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField(default=True, verbose_name='FLAG')),
                ('at_number', models.CharField(max_length=100, verbose_name='AT. No.')),
                ('date', models.DateField(verbose_name='Date')),
                ('date_of_commissionning', models.DateField(verbose_name='Date of Commissionning')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('contact_person', models.CharField(max_length=50, verbose_name='Contact Person')),
                ('fax', models.CharField(blank=True, max_length=50, null=True, verbose_name='FAX')),
                ('technical_parameters', django_quill.fields.QuillField(blank=True, null=True)),
                ('present_usage', django_quill.fields.QuillField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.shop', verbose_name='Location')),
                ('machine_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipment.equipment', verbose_name='Identification Number')),
            ],
            options={
                'verbose_name': 'EquipmentStatics',
                'verbose_name_plural': 'EquipmentStatics',
            },
        ),
    ]
